=== heisehuanyin/SBSAsync/format.dtd
<!ELEMENT store (page*)>
<!ELEMENT page (list-node*, map-node*)>
<!ELEMENT list-node (value-store*)>
<!ATTLIST list-node name CDATA #REQUIRED>
<!ELEMENT value-store EMPTY>
<!ATTLIST value-store name CDATA #IMPLIED>
<!ATTLIST value-store value CDATA #REQUIRED>
<!ELEMENT map-node (value-store*)>
<!ATTLIST map-node name CDATA #REQUIRED>
<!ATTLIST page id ID #REQUIRED>

=== heisehuanyin/SBSAsync/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE store SYSTEM "format.dtd">
<store>
    <page id="about">
        <list-node name="content">
            <value-store value="String-0"/>
            <value-store value="String-1"/>
            <value-store value="String-2"/>
            <value-store value="String-3"/>
            <value-store value="String-4"/>
        </list-node>
        <map-node name="maps">
            <value-store name="key1" value="value1"/>
            <value-store name="key2" value="value2"/>
            <value-store name="key0" value="value0"/>
            <value-store name="key3" value="value3"/>
            <value-store name="key4" value="value4"/>
        </map-node>
    </page>
</store>
